create table if not exists public.daily_checks (
  id bigint generated by default as identity primary key,
  driver_id bigint not null,
  entry_date text not null,
  checked_at timestamptz not null default now(),
  reg_number text not null,
  status text not null check (status in ('no_defects', 'defect_reported')),
  safe_to_drive boolean not null default true,
  answers jsonb not null default '[]'::jsonb,
  defects jsonb not null default '[]'::jsonb,
  repaired boolean not null default false,
  repaired_at timestamptz,
  boss_note text not null default '',
  created_at timestamptz not null default now()
);

alter table public.daily_checks
  add column if not exists repaired boolean not null default false,
  add column if not exists repaired_at timestamptz,
  add column if not exists boss_note text not null default '';

create table if not exists public.daily_check_photos (
  id bigint generated by default as identity primary key,
  daily_check_id bigint not null references public.daily_checks(id) on delete cascade,
  driver_id bigint not null,
  question_id text not null,
  photo_url text not null,
  photo_path text,
  created_at timestamptz not null default now()
);

create index if not exists daily_checks_driver_date_idx
  on public.daily_checks (driver_id, entry_date desc, checked_at desc);

create index if not exists daily_check_photos_driver_check_idx
  on public.daily_check_photos (driver_id, daily_check_id);

create index if not exists daily_check_photos_check_id_idx
  on public.daily_check_photos (daily_check_id);

alter table public.daily_checks disable row level security;
alter table public.daily_check_photos disable row level security;

grant select, insert, update, delete on public.daily_checks to anon, authenticated;
grant select, insert, update, delete on public.daily_check_photos to anon, authenticated;
grant usage, select on sequence public.daily_checks_id_seq to anon, authenticated;
grant usage, select on sequence public.daily_check_photos_id_seq to anon, authenticated;
